version: "3.1"
services:

  backend:
    image: tearust/gluon-website-backend:0.3
    container_name: gluon-backend
    ports:
      - 3002:3001
    volumes: 
      - ../gluon-docs:/tea-docs
    environment: 
      - NODE_ENV=prod
      - SERVER_PORT=3001
    command: "node index.js"
    
  frontend:
    image: tearust/gluon-website-frontend:0.3
    container_name: gluon-frontend
    # volumes:
      # - /letsencrypt:/etc/letsencrypt
    ports:
      - 91:80
        
    
