version: "3.1"
services:

  backend:
    image: tearust/gluon-website-backend:0.1
    container_name: backend
    ports:
      - 3001:3001
    volumes: 
      - ../gluon-docs:/tea-docs
    environment: 
      - NODE_ENV=prod
      - SERVER_PORT=3001
    command: "node index.js"
    
  frontend:
    image: tearust/gluon-website-frontend:0.1
    container_name: frontend
    # volumes:
      # - /letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
        
    
