version: "3.1"
services:

  backend:
    image: tearust/gluon-website-backend:latest
    container_name: backend
    ports:
      - 3001:3001
    volumes: 
      - ../tea-docs:/tea-docs
    environment: 
      - NODE_ENV=prod
      - SERVER_PORT=3001
      - LAYER1_URL=ws://64.227.57.97:9944
      - LAYER1_ACCOUNT=Alice
    command: "node index.js"
    
  frontend:
    image: tearust/gluon-website-frontend:latest
    container_name: frontend
    volumes:
      # - /letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
        
    
